# Use the official Node.js image from the Docker Hub
FROM node:20

# Set the working directory
WORKDIR /Super-Rapid-Annotator-Multimodal-Annotation-Tool

# Copy the application code
COPY backend/ .

# Install dependencies
RUN npm i cors-anywhere

# Expose the port for the Node.js server
EXPOSE 8080

# Run the server
CMD ["node", "./backend/proxy_server.js"]
